version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./web:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "APP_DEBUG=true"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=kritb"
      - "MYSQL_ROOT_PASSWORD=p@ssw0rd"
    ports:
        - "33061:3306"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: kritb-phpmyadmin
      links:
      - "database:database"
      environment:
      - TESTSUITE_PASSWORD=p@ssw0rd
      - PMA_HOST=database
      ports:
      - 5555:80
      volumes:
      - /sessions

volumes:
  dbdata: